# Generated by Django 4.1.4 on 2022-12-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Menú', max_length=191)),
                ('enlace', models.CharField(help_text='Ruta Menú', max_length=191)),
                ('icono', models.CharField(blank=True, help_text='Icono del Menú', max_length=191, null=True)),
                ('padre', models.IntegerField(default=0, help_text='Padre del Menú')),
                ('orden', models.SmallIntegerField(blank=True, help_text='Orden de menú', null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de Acceso', max_length=191)),
                ('slug', models.CharField(help_text='Ruta Amigable Acceso', max_length=191)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de Acceso', max_length=191, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción Sexo', max_length=191)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, help_text='Fecha Creada')),
                ('fecha_modificada', models.DateTimeField(auto_now=True, help_text='Fecha Eliminada')),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'sexos',
            },
        ),
        migrations.CreateModel(
            name='TipoAcceso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de Acceso', max_length=191)),
                ('slug', models.CharField(help_text='Ruta Amigable Acceso', max_length=191)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de Acceso', max_length=191, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'tipo_accesos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, help_text='Código Tipo Documento', max_length=2, null=True)),
                ('nombre_corto', models.CharField(blank=True, help_text='Descripción Corta', max_length=191, null=True)),
                ('nombre_largo', models.CharField(blank=True, help_text='Descripción Larga', max_length=191, null=True)),
                ('longitud', models.PositiveSmallIntegerField(help_text='Longitud Documento')),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, help_text='Fecha Creada')),
                ('fecha_modificada', models.DateTimeField(auto_now=True, help_text='Fecha Eliminada')),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'tipo_documentos',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre de Rol', max_length=191, null=True)),
                ('slug', models.CharField(blank=True, help_text='Ruta Amigable Rol', max_length=191, null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de Rol', max_length=191, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
                ('acceso', models.ForeignKey(blank=True, help_text='Persona Usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, to='cuenta.tipoacceso')),
                ('menus', models.ManyToManyField(to='cuenta.menu')),
                ('permisos', models.ManyToManyField(to='cuenta.permiso')),
            ],
            options={
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(help_text='Número Documento', max_length=15)),
                ('nombres', models.CharField(help_text='Nombres', max_length=191)),
                ('apellidos', models.CharField(help_text='Apellidos', max_length=191)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=191, null=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, help_text='Fecha Creada')),
                ('fecha_modificada', models.DateTimeField(auto_now=True, help_text='Fecha Eliminada')),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
                ('sexo', models.ForeignKey(blank=True, help_text='Sexo Persona', null=True, on_delete=django.db.models.deletion.RESTRICT, to='cuenta.sexo')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cuenta.tipodocumento')),
            ],
            options={
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Correo Electrónico', max_length=191, null=True, unique=True)),
                ('username', models.CharField(help_text='Nombre Usuario', max_length=191, unique=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de Perfil', max_length=191, null=True, upload_to='media/usuarios/')),
                ('es_activo', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=191, null=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, help_text='Fecha Creada')),
                ('fecha_modificada', models.DateTimeField(auto_now=True, help_text='Fecha Eliminada')),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('persona', models.OneToOneField(blank=True, help_text='Persona Usuario', null=True, on_delete=django.db.models.deletion.RESTRICT, to='cuenta.persona')),
                ('roles', models.ManyToManyField(to='cuenta.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
