import './assets/plugins/jquery/jquery.min.js'
import './assets/plugins/jquery-ui/jquery-ui.min.js'
import './assets/plugins/bootstrap/js/bootstrap.bundle.min.js'
import './assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'
import './assets/app/js/adminlte.js'